development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
