development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  img_up_aws_s3_access_key_id: <%= ENV['IMG_UP_AWS_S3_ACCESS_KEY_ID'] %>
  img_up_aws_s3_secret_access_key: <%= ENV['IMG_UP_AWS_S3_SECRET_ACCESS_KEY'] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
